baseURL = "http://www.thiagovalentim.me/"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Thiago Valentim"
    description = " "
    keywords = " "
    info = "Cientista de dados e Professor de Matemática"
    avatarurl = "images/Eu.jpg"
    #gravatar = "thiagomadridd@gmail.com"
    footercontent = "Natal - Rio Grande do Norte - Brasil"

    dateformat = "02/01/2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ThiagoValentimMarques"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/thiago-valentim-aa1282171/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/thiagomadridd"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 4
    url = "https://www.instagram.com/thiago_valentim1986/"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook-square"
    weight = 5
    url = "https://www.facebook.com/thiago.valentim.391"


    [languages]
    [languages.pt-br]
        languagename = "Português"
        title = "THIAGO VALENTIM"

        [languages.pt-br.params]
            author = "Thiago Valentim"
            info = "Cientista de Dados e Professor de Matemática"
            description = " "
            keywords = " "
            footercontent = "Natal - Rio Grande do Norte - Brasil"

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "post/"

            [[languages.pt-br.menu.main]]
            name = "Publicações"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "contact/"
